/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'effect' : IDL.Null,
  'filter' : IDL.Null,
  'template' : IDL.Null,
  'image' : IDL.Null,
  'sticker' : IDL.Null,
});
export const MediaEntry = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'mediaType' : MediaType,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobType = IDL.Variant({
  'tts' : IDL.Null,
  'autoCut' : IDL.Null,
  'captions' : IDL.Null,
  'textToVideo' : IDL.Null,
  'remover' : IDL.Null,
  'imageToVideo' : IDL.Null,
});
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const AIJob = IDL.Record({
  'id' : IDL.Text,
  'status' : JobStatus,
  'inputData' : IDL.Opt(ExternalBlob),
  'owner' : IDL.Principal,
  'jobType' : JobType,
  'createdAt' : Time,
  'resultData' : IDL.Opt(ExternalBlob),
});
export const Language = IDL.Variant({
  'en' : IDL.Null,
  'hi' : IDL.Null,
  'te' : IDL.Null,
});
export const Caption = IDL.Record({
  'text' : IDL.Text,
  'language' : Language,
  'timestamp' : IDL.Nat,
});
export const CreateProjectArgs = IDL.Record({
  'name' : IDL.Text,
  'captions' : IDL.Vec(Caption),
  'mediaFiles' : IDL.Vec(MediaEntry),
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'captions' : IDL.Vec(Caption),
  'mediaFiles' : IDL.Vec(MediaEntry),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMediaEntry' : IDL.Func([MediaEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAIJob' : IDL.Func([JobType, IDL.Opt(ExternalBlob)], [AIJob], []),
  'createProject' : IDL.Func([CreateProjectArgs], [Project], []),
  'deleteMediaEntry' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllJobs' : IDL.Func([], [IDL.Vec(AIJob)], ['query']),
  'getAllMediaByType' : IDL.Func([MediaType], [IDL.Vec(MediaEntry)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(AIJob)], ['query']),
  'getMediaEntry' : IDL.Func([IDL.Text], [IDL.Opt(MediaEntry)], ['query']),
  'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getUserJobs' : IDL.Func([], [IDL.Vec(AIJob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([IDL.Principal], [IDL.Vec(Project)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateJobStatus' : IDL.Func(
      [IDL.Text, JobStatus, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateProject' : IDL.Func([IDL.Text, CreateProjectArgs], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'effect' : IDL.Null,
    'filter' : IDL.Null,
    'template' : IDL.Null,
    'image' : IDL.Null,
    'sticker' : IDL.Null,
  });
  const MediaEntry = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'mediaType' : MediaType,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'tts' : IDL.Null,
    'autoCut' : IDL.Null,
    'captions' : IDL.Null,
    'textToVideo' : IDL.Null,
    'remover' : IDL.Null,
    'imageToVideo' : IDL.Null,
  });
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const AIJob = IDL.Record({
    'id' : IDL.Text,
    'status' : JobStatus,
    'inputData' : IDL.Opt(ExternalBlob),
    'owner' : IDL.Principal,
    'jobType' : JobType,
    'createdAt' : Time,
    'resultData' : IDL.Opt(ExternalBlob),
  });
  const Language = IDL.Variant({
    'en' : IDL.Null,
    'hi' : IDL.Null,
    'te' : IDL.Null,
  });
  const Caption = IDL.Record({
    'text' : IDL.Text,
    'language' : Language,
    'timestamp' : IDL.Nat,
  });
  const CreateProjectArgs = IDL.Record({
    'name' : IDL.Text,
    'captions' : IDL.Vec(Caption),
    'mediaFiles' : IDL.Vec(MediaEntry),
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'captions' : IDL.Vec(Caption),
    'mediaFiles' : IDL.Vec(MediaEntry),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMediaEntry' : IDL.Func([MediaEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAIJob' : IDL.Func([JobType, IDL.Opt(ExternalBlob)], [AIJob], []),
    'createProject' : IDL.Func([CreateProjectArgs], [Project], []),
    'deleteMediaEntry' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllJobs' : IDL.Func([], [IDL.Vec(AIJob)], ['query']),
    'getAllMediaByType' : IDL.Func(
        [MediaType],
        [IDL.Vec(MediaEntry)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(AIJob)], ['query']),
    'getMediaEntry' : IDL.Func([IDL.Text], [IDL.Opt(MediaEntry)], ['query']),
    'getMyProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getUserJobs' : IDL.Func([], [IDL.Vec(AIJob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Project)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateJobStatus' : IDL.Func(
        [IDL.Text, JobStatus, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateProject' : IDL.Func([IDL.Text, CreateProjectArgs], [], []),
  });
};

export const init = ({ IDL }) => { return []; };