/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIJob {
  'id' : string,
  'status' : JobStatus,
  'inputData' : [] | [ExternalBlob],
  'owner' : Principal,
  'jobType' : JobType,
  'createdAt' : Time,
  'resultData' : [] | [ExternalBlob],
}
export interface Caption {
  'text' : string,
  'language' : Language,
  'timestamp' : bigint,
}
export interface CreateProjectArgs {
  'name' : string,
  'captions' : Array<Caption>,
  'mediaFiles' : Array<MediaEntry>,
}
export type ExternalBlob = Uint8Array;
export type JobStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type JobType = { 'tts' : null } |
  { 'autoCut' : null } |
  { 'captions' : null } |
  { 'textToVideo' : null } |
  { 'remover' : null } |
  { 'imageToVideo' : null };
export type Language = { 'en' : null } |
  { 'hi' : null } |
  { 'te' : null };
export interface MediaEntry {
  'id' : string,
  'file' : ExternalBlob,
  'mediaType' : MediaType,
  'category' : string,
}
export type MediaType = { 'audio' : null } |
  { 'video' : null } |
  { 'effect' : null } |
  { 'filter' : null } |
  { 'template' : null } |
  { 'image' : null } |
  { 'sticker' : null };
export interface Project {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'captions' : Array<Caption>,
  'mediaFiles' : Array<MediaEntry>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMediaEntry' : ActorMethod<[MediaEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAIJob' : ActorMethod<[JobType, [] | [ExternalBlob]], AIJob>,
  'createProject' : ActorMethod<[CreateProjectArgs], Project>,
  'deleteMediaEntry' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllJobs' : ActorMethod<[], Array<AIJob>>,
  'getAllMediaByType' : ActorMethod<[MediaType], Array<MediaEntry>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[string], [] | [AIJob]>,
  'getMediaEntry' : ActorMethod<[string], [] | [MediaEntry]>,
  'getMyProjects' : ActorMethod<[], Array<Project>>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getUserJobs' : ActorMethod<[], Array<AIJob>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[Principal], Array<Project>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateJobStatus' : ActorMethod<
    [string, JobStatus, [] | [ExternalBlob]],
    undefined
  >,
  'updateProject' : ActorMethod<[string, CreateProjectArgs], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];