/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface Caption {
    text: string;
    language: Language;
    timestamp: bigint;
}
export interface AIJob {
    id: string;
    status: JobStatus;
    inputData?: ExternalBlob;
    owner: Principal;
    jobType: JobType;
    createdAt: Time;
    resultData?: ExternalBlob;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MediaEntry {
    id: string;
    file: ExternalBlob;
    mediaType: MediaType;
    category: string;
}
export interface CreateProjectArgs {
    name: string;
    captions: Array<Caption>;
    mediaFiles: Array<MediaEntry>;
}
export interface Project {
    id: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    captions: Array<Caption>;
    mediaFiles: Array<MediaEntry>;
}
export enum JobStatus {
    pending = "pending",
    complete = "complete",
    processing = "processing",
    failed = "failed"
}
export enum JobType {
    tts = "tts",
    autoCut = "autoCut",
    captions = "captions",
    textToVideo = "textToVideo",
    remover = "remover",
    imageToVideo = "imageToVideo"
}
export enum Language {
    en = "en",
    hi = "hi",
    te = "te"
}
export enum MediaType {
    audio = "audio",
    video = "video",
    effect = "effect",
    filter = "filter",
    template = "template",
    image = "image",
    sticker = "sticker"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMediaEntry(media: MediaEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAIJob(jobType: JobType, inputData: ExternalBlob | null): Promise<AIJob>;
    createProject(args: CreateProjectArgs): Promise<Project>;
    deleteMediaEntry(id: string): Promise<void>;
    deleteProject(id: string): Promise<void>;
    getAllJobs(): Promise<Array<AIJob>>;
    getAllMediaByType(mediaType: MediaType): Promise<Array<MediaEntry>>;
    getAllProjects(): Promise<Array<Project>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJob(jobId: string): Promise<AIJob | null>;
    getMediaEntry(id: string): Promise<MediaEntry | null>;
    getMyProjects(): Promise<Array<Project>>;
    getProject(id: string): Promise<Project | null>;
    getUserJobs(): Promise<Array<AIJob>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProjects(user: Principal): Promise<Array<Project>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateJobStatus(jobId: string, status: JobStatus, resultData: ExternalBlob | null): Promise<void>;
    updateProject(id: string, args: CreateProjectArgs): Promise<void>;
}
import type { AIJob as _AIJob, Caption as _Caption, CreateProjectArgs as _CreateProjectArgs, ExternalBlob as _ExternalBlob, JobStatus as _JobStatus, JobType as _JobType, Language as _Language, MediaEntry as _MediaEntry, MediaType as _MediaType, Project as _Project, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMediaEntry(arg0: MediaEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaEntry(await to_candid_MediaEntry_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaEntry(await to_candid_MediaEntry_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAIJob(arg0: JobType, arg1: ExternalBlob | null): Promise<AIJob> {
        if (this.processError) {
            try {
                const result = await this.actor.createAIJob(to_candid_JobType_n15(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AIJob_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAIJob(to_candid_JobType_n15(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AIJob_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: CreateProjectArgs): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(await to_candid_CreateProjectArgs_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Project_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(await to_candid_CreateProjectArgs_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Project_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMediaEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaEntry(arg0);
            return result;
        }
    }
    async deleteProject(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAllJobs(): Promise<Array<AIJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMediaByType(arg0: MediaType): Promise<Array<MediaEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMediaByType(to_candid_MediaType_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMediaByType(to_candid_MediaType_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<AIJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaEntry(arg0: string): Promise<MediaEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaEntry(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaEntry(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProjects();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProjects();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: string): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserJobs(): Promise<Array<AIJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserJobs();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserJobs();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProjects(arg0: Principal): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProjects(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProjects(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateJobStatus(arg0: string, arg1: JobStatus, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n54(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobStatus(arg0, to_candid_JobStatus_n54(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateProject(arg0: string, arg1: CreateProjectArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, await to_candid_CreateProjectArgs_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, await to_candid_CreateProjectArgs_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_AIJob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIJob): Promise<AIJob> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Caption_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Caption): Caption {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_JobStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaEntry_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaEntry): Promise<MediaEntry> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_Project_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Promise<Project> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIJob]): Promise<AIJob | null> {
    return value.length === 0 ? null : await from_candid_AIJob_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaEntry]): Promise<MediaEntry | null> {
    return value.length === 0 ? null : await from_candid_MediaEntry_n42(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Promise<Project | null> {
    return value.length === 0 ? null : await from_candid_Project_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _JobStatus;
    inputData: [] | [_ExternalBlob];
    owner: Principal;
    jobType: _JobType;
    createdAt: _Time;
    resultData: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    status: JobStatus;
    inputData?: ExternalBlob;
    owner: Principal;
    jobType: JobType;
    createdAt: Time;
    resultData?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_JobStatus_n20(_uploadFile, _downloadFile, value.status),
        inputData: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.inputData)),
        owner: value.owner,
        jobType: from_candid_JobType_n24(_uploadFile, _downloadFile, value.jobType),
        createdAt: value.createdAt,
        resultData: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.resultData))
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    name: string;
    createdAt: _Time;
    captions: Array<_Caption>;
    mediaFiles: Array<_MediaEntry>;
}): Promise<{
    id: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    captions: Array<Caption>;
    mediaFiles: Array<MediaEntry>;
}> {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        captions: from_candid_vec_n36(_uploadFile, _downloadFile, value.captions),
        mediaFiles: await from_candid_vec_n41(_uploadFile, _downloadFile, value.mediaFiles)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    language: _Language;
    timestamp: bigint;
}): {
    text: string;
    language: Language;
    timestamp: bigint;
} {
    return {
        text: value.text,
        language: from_candid_Language_n39(_uploadFile, _downloadFile, value.language),
        timestamp: value.timestamp
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: _ExternalBlob;
    mediaType: _MediaType;
    category: string;
}): Promise<{
    id: string;
    file: ExternalBlob;
    mediaType: MediaType;
    category: string;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.file),
        mediaType: from_candid_MediaType_n44(_uploadFile, _downloadFile, value.mediaType),
        category: value.category
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
} | {
    processing: null;
} | {
    failed: null;
}): JobStatus {
    return "pending" in value ? JobStatus.pending : "complete" in value ? JobStatus.complete : "processing" in value ? JobStatus.processing : "failed" in value ? JobStatus.failed : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tts: null;
} | {
    autoCut: null;
} | {
    captions: null;
} | {
    textToVideo: null;
} | {
    remover: null;
} | {
    imageToVideo: null;
}): JobType {
    return "tts" in value ? JobType.tts : "autoCut" in value ? JobType.autoCut : "captions" in value ? JobType.captions : "textToVideo" in value ? JobType.textToVideo : "remover" in value ? JobType.remover : "imageToVideo" in value ? JobType.imageToVideo : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    en: null;
} | {
    hi: null;
} | {
    te: null;
}): Language {
    return "en" in value ? Language.en : "hi" in value ? Language.hi : "te" in value ? Language.te : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audio: null;
} | {
    video: null;
} | {
    effect: null;
} | {
    filter: null;
} | {
    template: null;
} | {
    image: null;
} | {
    sticker: null;
}): MediaType {
    return "audio" in value ? MediaType.audio : "video" in value ? MediaType.video : "effect" in value ? MediaType.effect : "filter" in value ? MediaType.filter : "template" in value ? MediaType.template : "image" in value ? MediaType.image : "sticker" in value ? MediaType.sticker : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Caption>): Array<Caption> {
    return value.map((x)=>from_candid_Caption_n37(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaEntry>): Promise<Array<MediaEntry>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaEntry_n42(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AIJob>): Promise<Array<AIJob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AIJob_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Promise<Array<Project>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Project_n34(_uploadFile, _downloadFile, x)));
}
function to_candid_Caption_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Caption): _Caption {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateProjectArgs_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProjectArgs): Promise<_CreateProjectArgs> {
    return await to_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JobStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Language_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
async function to_candid_MediaEntry_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaEntry): Promise<_MediaEntry> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    captions: Array<Caption>;
    mediaFiles: Array<MediaEntry>;
}): Promise<{
    name: string;
    captions: Array<_Caption>;
    mediaFiles: Array<_MediaEntry>;
}> {
    return {
        name: value.name,
        captions: to_candid_vec_n28(_uploadFile, _downloadFile, value.captions),
        mediaFiles: await to_candid_vec_n33(_uploadFile, _downloadFile, value.mediaFiles)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    language: Language;
    timestamp: bigint;
}): {
    text: string;
    language: _Language;
    timestamp: bigint;
} {
    return {
        text: value.text,
        language: to_candid_Language_n31(_uploadFile, _downloadFile, value.language),
        timestamp: value.timestamp
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: ExternalBlob;
    mediaType: MediaType;
    category: string;
}): Promise<{
    id: string;
    file: _ExternalBlob;
    mediaType: _MediaType;
    category: string;
}> {
    return {
        id: value.id,
        file: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file),
        mediaType: to_candid_MediaType_n11(_uploadFile, _downloadFile, value.mediaType),
        category: value.category
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    audio: null;
} | {
    video: null;
} | {
    effect: null;
} | {
    filter: null;
} | {
    template: null;
} | {
    image: null;
} | {
    sticker: null;
} {
    return value == MediaType.audio ? {
        audio: null
    } : value == MediaType.video ? {
        video: null
    } : value == MediaType.effect ? {
        effect: null
    } : value == MediaType.filter ? {
        filter: null
    } : value == MediaType.template ? {
        template: null
    } : value == MediaType.image ? {
        image: null
    } : value == MediaType.sticker ? {
        sticker: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    tts: null;
} | {
    autoCut: null;
} | {
    captions: null;
} | {
    textToVideo: null;
} | {
    remover: null;
} | {
    imageToVideo: null;
} {
    return value == JobType.tts ? {
        tts: null
    } : value == JobType.autoCut ? {
        autoCut: null
    } : value == JobType.captions ? {
        captions: null
    } : value == JobType.textToVideo ? {
        textToVideo: null
    } : value == JobType.remover ? {
        remover: null
    } : value == JobType.imageToVideo ? {
        imageToVideo: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    en: null;
} | {
    hi: null;
} | {
    te: null;
} {
    return value == Language.en ? {
        en: null
    } : value == Language.hi ? {
        hi: null
    } : value == Language.te ? {
        te: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    pending: null;
} | {
    complete: null;
} | {
    processing: null;
} | {
    failed: null;
} {
    return value == JobStatus.pending ? {
        pending: null
    } : value == JobStatus.complete ? {
        complete: null
    } : value == JobStatus.processing ? {
        processing: null
    } : value == JobStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Caption>): Array<_Caption> {
    return value.map((x)=>to_candid_Caption_n29(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MediaEntry>): Promise<Array<_MediaEntry>> {
    return await Promise.all(value.map(async (x)=>await to_candid_MediaEntry_n8(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
